# Generated by Django 5.2.4 on 2025-07-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
    ]
