# Generated by Django 5.2.4 on 2025-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
