# Generated by Django 5.2.4 on 2025-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyTracker', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('entertaiment', 'Развлечение'), ('food', 'Еда'), ('shopping', 'Магазин'), ('other', 'Разное')], max_length=20, null=True),
        ),
    ]
