# Generated by Django 5.2.4 on 2025-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyTracker', '0003_remove_money_description_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
