# Generated by Django 5.2.4 on 2025-07-21 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyTracker', '0004_alter_money_amount_alter_transaction_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money',
            new_name='Wallet',
        ),
    ]
