# Generated by Django 5.2.4 on 2025-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyTracker', '0006_category_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('entertaiment', 'Развлечение'), ('food', 'Еда'), ('shopping', 'Магазин')], default='other'),
        ),
    ]
